apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: configmap
    app.kubernetes.io/instance: config
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: kapacity
    app.kubernetes.io/part-of: kapacity
    app.kubernetes.io/managed-by: kustomize
data:
  prometheus-metrics-config.yaml: |
    resourceRules:
      cpu:
        containerQuery: sum by (<<.GroupBy>>) (irate(container_cpu_usage_seconds_total{container!="",container!="POD",<<.LabelMatchers>>}[3m]))
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        containerLabel: container
      memory:
        containerQuery: sum by (<<.GroupBy>>) (container_memory_working_set_bytes{container!="",container!="POD",<<.LabelMatchers>>})
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        containerLabel: container
      window: 3m
    externalRules:
    - seriesQuery: '{__name__="kube_pod_status_ready"}'
      metricsQuery: sum(<<.Series>>{condition="true",<<.LabelMatchers>>})
      name:
        as: ready_pods_count
      resources:
        overrides:
          namespace:
            resource: namespace
    workloadPodNamePatterns:
    - group: apps
      kind: ReplicaSet
      pattern: ^%s-[a-z0-9]+$
    - group: apps
      kind: Deployment
      pattern: ^%s-[a-z0-9]+-[a-z0-9]+$
    - group: apps
      kind: StatefulSet
      pattern: ^%s-[0-9]+$
