apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: algorithm-job-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kapacity
    app.kubernetes.io/part-of: kapacity
    app.kubernetes.io/managed-by: kustomize
  name: algorithm-job-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: algorithm-job-role
subjects:
- kind: ServiceAccount
  name: algorithm-job
  namespace: system
