---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
- apiGroups:
  - '*'
  resources:
  - '*/scale'
  verbs:
  - get
  - update
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - horizontalportraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - horizontalportraits/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - horizontalportraits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - intelligenthorizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - intelligenthorizontalpodautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - intelligenthorizontalpodautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - replicaprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - replicaprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kapacitystack.io
  resources:
  - replicaprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
