apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kapacity
    app.kubernetes.io/part-of: kapacity
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: algorithm-job
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kapacity
    app.kubernetes.io/part-of: kapacity
    app.kubernetes.io/managed-by: kustomize
  name: algorithm-job
  namespace: system
